on:  
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: compress
        working-directory: ./src
        run: |
          npm install uglify-js -g
          for i in *.js; do uglifyjs -c -m -o $i $i; done
      - name: create manifest-common
        run: cat manifest-template.json | jq -c '.version = "${{ github.ref_name }}"' > manifest-common.json
      - name: chrome
        run: |
          mkdir chrome
          cp -r src/* chrome
          jq -c -s '.[0] * .[1]' manifest-common.json manifest-chrome.json > chrome/manifest.json
          cd chrome
          zip ../Purdue-Auto-Login-Chrome.zip *
      - name: firefox
        run: |
          mkdir firefox
          cp -r src/* firefox
          jq -c -s '.[0] * .[1]' manifest-common.json manifest-firefox.json > firefox/manifest.json          
          cd firefox
          zip ../Purdue-Auto-Login-Firefox.zip *
      - name: edge
        run: |
          mkdir edge
          cp -r src/* edge
          jq -c -s '.[0] * .[1]' manifest-common.json manifest-edge.json > edge/manifest.json          
          cd edge
          zip ../Purdue-Auto-Login-Edge.zip *
      - name: Release
        run: gh release create ${{ github.ref_name }} Purdue-Auto-Login-Chrome.zip Purdue-Auto-Login-Firefox.zip Purdue-Auto-Login-Edge.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
